version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: annotation_project/Dockerfile
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./annotation_project:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: anno-client/Dockerfile
    env_file: .env
    ports:
      - "3000:80"   # nginx serving build
    depends_on:
      - backend

volumes:
  pgdata:
