# Generated by Django 5.1.6 on 2025-07-17 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Particle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="sentence",
            name="file",
        ),
        migrations.RemoveField(
            model_name="sentence",
            name="sent_id",
        ),
        migrations.CreateModel(
            name="Heading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.domain"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sentence",
            name="heading",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.heading",
            ),
        ),
        migrations.DeleteModel(
            name="File",
        ),
    ]
