# Generated by Django 5.1.6 on 2025-07-18 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_particle_remove_sentence_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentence",
            name="external_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="heading",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.heading"
            ),
        ),
    ]
