# Generated by Django 5.1.6 on 2025-07-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sentence_external_id_alter_sentence_heading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentence",
            name="external_id",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
