# Generated by Django 5.1.6 on 2025-07-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_sentence_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heading",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
