# Generated by Django 5.1.6 on 2025-07-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_heading_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sentence",
            old_name="external_id",
            new_name="sentence_id",
        ),
    ]
