# Generated by Django 5.1.6 on 2025-07-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_external_to_sentence"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentence",
            name="newsentence",
            field=models.TextField(blank=True, null=True),
        ),
    ]
