# Generated by Django 5.1.6 on 2025-07-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_sentence_newsentence"),
    ]

    operations = [
        migrations.AddField(
            model_name="particle",
            name="english",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
