# Generated by Django 5.1.6 on 2025-07-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_particle_english"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Annotation",
        ),
    ]
