# Generated by Django 5.1.6 on 2025-07-23 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_delete_annotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentence",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claimed_sentences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sentence",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
