# Generated by Django 5.1.6 on 2025-07-23 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_sentence_assigned_to_sentence_locked_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sentence",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="sentence",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_sentences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
